### ISSUE TITLE
English Dictionary not supporting

### ISSUE THREAD

**Issue by Amita27** [segabor/Hunspell#1]
I was trying using "dict-en.oxt & english.aff"(English affix and dictionaries.) to get English language support with Hunspell, it is showing blank array for suggestions with no errors.

Please suggest me, how can I use Hunspell for International English Language support.
There is no installation problem I hope, as it is working properly with "Hungarian affix and dictionary"

**Comment by segabor** [comment]
Hi,

It is possible that oxt format is not compatible with hunspell library. I googled up a list of hunspell dictionaries. Please download one from [here](http://cgit.freedesktop.org/libreoffice/dictionaries/tree/en) and give a try.

**Comment by segabor** [comment]
Did you have a chance to give a try with the dictionary downloaded from the given URL? I will close the ticket soon assuming this is a non-issue.

**Comment by segabor** [comment]
Please open a new issue if you still experience the issue. I close this due to inactivity.

**Comment by Amita27** [comment]
Thanks, got the expected output. Apologies  for late reply.

**Comment by segabor** [comment]
No problem!
