### ISSUE TITLE
Usage with a paragraph of text?

### ISSUE THREAD

**Issue by oyeanuj** [segabor/Hunspell#7]
Hi @segabor, firstly, thank you for creating this library. I was curious if there was any example of using it with a paragraph of text? Or is it only meant to be used one word at a time and get suggestions for that word?

Is there a performant way to feed in a paragraph, and get a hash of the problem-word, its offset, and its suggestions?

Thank you!

**Comment by segabor** [comment]
Hi,

To be honest, I used Hunspell for simple word-wise feedback. I don't know if hunspell lib has such a service.

UPDATE: according to this [link](https://github.com/rexxars/nodehun-sentences), hunspell provides only low-level API so the feature you want has to be implemented on top of it.

**Comment by oyeanuj** [comment]
@segabor, thank you for the quick response! I'll check out that link and investigate more!
